travis:
  secure:
    BINSTAR_TOKEN: N+5qhbKGs2kJBkwtl2wnNqHZUAQgt3ah4EJlVvPFGEHpdsQnJ9HWqPr2aWedc8NI/3b0uMaP3/54QVToCI2uOVumodROCxqjWb/S0hMxYL3fngQItLSKsngWdyQNLW2Vx2C7NCGiFrUTMAWao2xc4W0vP3l28/f7wCJS7w443JtbvZr+W5ZItfIc1u4QITp5+/4ZqzFktTaSYqg1w5g859eMQZ+ZCYp684EnAlaz4j3TYWTtRSAfQoebzF4fT+Fe/Qwr7WO91iuPdX3gz1LX/duP1cXS2grFx7EUiCWJ3zrqiBr5oNXWr6dWGsLqaVqlULvrAsJJ4tdLzJrsz5D3RV+ogHLbfQ1U+f16fB+Le/W3RvXHNLPUChdx/ieFrveAkymnBcImRQJVf3eNKYuj3vxf0f8qge0D9D0w9k0H5223VkQpOvCBmcgPCxEwrmnB1tIhkd6WqLaqFUStQ3WHHlJeMkM0DpuYKAq/Hf/X5DBmzFCKddTQKTt0a2OHRWNXcKvF0c32YMuVo18AFym8eA5J/d1KMJh9AsobmKua5LcxhAb5MEhpGTr/I13HVpi4JnTbN+ulQ84ljCJKhHhSu4Jpmyf+bqAw51sjicCfHmblaXINIvyKIysx2i0/nl72FKif9xWSZaUd0xg0Z2zTLpYufjbht+bxBjys7MWQqmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
